//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllowanceMaster
    {
        public int AllowanceId { get; set; }
        public string AllowanceType { get; set; }
        public string ValueMethod { get; set; }
        public string AllowanceHead { get; set; }
        public Nullable<decimal> AllowanceAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCreated { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
