//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRYLIST
    {
        public int ID { get; set; }
        public string ISO { get; set; }
        public string NAME { get; set; }
        public string NICENAME { get; set; }
        public string ISO3 { get; set; }
        public Nullable<int> NUMCODE { get; set; }
        public int PHONECODE { get; set; }
    }
}
