//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSI
    {
        public int EmployeeSIId { get; set; }
        public int EmployeeCode { get; set; }
        public string CurrentPosting { get; set; }
        public string BankType { get; set; }
        public string NameOfBanks { get; set; }
        public string BankBranch { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string PFA { get; set; }
        public string RSAPinNo { get; set; }
        public string SalaryScale { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual EmployeeGI EmployeeGI { get; set; }
    }
}
