//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class EmployeeGI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeGI()
        {
            this.AnnualLeaves = new HashSet<AnnualLeave>();
            this.AnnualLeaves1 = new HashSet<AnnualLeave>();
            this.CasualLeaves = new HashSet<CasualLeave>();
            this.CasualLeaves1 = new HashSet<CasualLeave>();
            this.EmployeeAIs = new HashSet<EmployeeAI>();
            this.EmployeeMIs = new HashSet<EmployeeMI>();
            this.EmployeePIs = new HashSet<EmployeePI>();
            this.EmployeeSIs = new HashSet<EmployeeSI>();
            this.GraduateAttachmentForms = new HashSet<GraduateAttachmentForm>();
            this.GraduateAttachmentForms1 = new HashSet<GraduateAttachmentForm>();
            this.LeaveRoasterJuniorStaffs = new HashSet<LeaveRoasterJuniorStaff>();
            this.NyscFinalClearances = new HashSet<NyscFinalClearance>();
            this.NyscFinalClearances1 = new HashSet<NyscFinalClearance>();
            this.NyscMonthlyClearances = new HashSet<NyscMonthlyClearance>();
            this.NyscMonthlyClearances1 = new HashSet<NyscMonthlyClearance>();
        }

        public int EmployeeGIId { get; set; }
        public int EmployeeCode { get; set; }
        public string Rank { get; set; }
        public string File_No { get; set; }
        public Nullable<int> Grade_Level { get; set; }
        public Nullable<int> Step { get; set; }
        public string Cadre { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Surname { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Marital_Status { get; set; }
        public string Maiden_Name { get; set; }
        public string Spouse_Name { get; set; }
        public string StateOfOrigin { get; set; }
        public string LGA { get; set; }
        public string Home_Town { get; set; }
        public string Religion { get; set; }
        public string ContactHomeAddress { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> FirstAppointmentDate { get; set; }
        public string FirstAppointmentLocation { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public System.DateTime DateOfRetirement { get; set; }
        public Nullable<System.DateTime> LastPromotionDate { get; set; }
        public string Unit_Research { get; set; }
        public string Section { get; set; }
        public Nullable<int> LeaveDays { get; set; }
        public Nullable<System.DateTime> Leave_fromDate { get; set; }
        public Nullable<System.DateTime> Leave_ToDate { get; set; }
        public string EmployeePhoto { get; set; }
        public string StationOfDeployment { get; set; }
        public string Programmes { get; set; }
        public string Unit_Services { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }

        [NotMapped]
        [DisplayName("Upload Passport Photo Of Employee")]
        [DataType(DataType.Upload)]
        //[RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.png|.jpg|.gif)$", ErrorMessage = "Only Image files allowed.")]
        public HttpPostedFileBase EmployeePhotoImage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnualLeave> AnnualLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnualLeave> AnnualLeaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasualLeave> CasualLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasualLeave> CasualLeaves1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAI> EmployeeAIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeMI> EmployeeMIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePI> EmployeePIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSI> EmployeeSIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GraduateAttachmentForm> GraduateAttachmentForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GraduateAttachmentForm> GraduateAttachmentForms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRoasterJuniorStaff> LeaveRoasterJuniorStaffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NyscFinalClearance> NyscFinalClearances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NyscFinalClearance> NyscFinalClearances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NyscMonthlyClearance> NyscMonthlyClearances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NyscMonthlyClearance> NyscMonthlyClearances1 { get; set; }
    }
}
