//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePI
    {
        public int EmployeePIId { get; set; }
        public int EmployeeCode { get; set; }
        public string EmpEmailId { get; set; }
        public string PermanentAddress { get; set; }
        public string MobileNo { get; set; }
        public string EmailIdKin { get; set; }
        public string KinName { get; set; }
        public string AddressNextOfKin { get; set; }
        public string StateNextOfKin { get; set; }
        public string LGAextOfKin { get; set; }
        public string Relation { get; set; }
        public string PhoneNoNextOfKin { get; set; }
        public string NameOfStaffBenificiary { get; set; }
        public string PhoneOfStaffBenificiary { get; set; }
        public string AddressOfStaffBenificiary { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual EmployeeGI EmployeeGI { get; set; }
    }
}
