//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int RecordId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string ItemName { get; set; }
        public string ItemCat { get; set; }
        public Nullable<int> UomId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string ItemRate { get; set; }
        public string ItemTax { get; set; }
        public string ItemImage { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string ItemDesc { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
