//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveLedger
    {
        public int LeaveLogId { get; set; }
        public int EmployeeCode { get; set; }
        public string LeaveType { get; set; }
        public decimal ConsumedLeaves { get; set; }
        public decimal BalanceLeaves { get; set; }
        public string FiscalYear { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
