//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRoasterJuniorStaff
    {
        public int Id { get; set; }
        public int EmployeeCode { get; set; }
        public Nullable<int> SNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> NoOfDay { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string FileNo { get; set; }
        public string Contiss { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual EmployeeGI EmployeeGI { get; set; }
    }
}
