//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrequalificationScoring
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string ProjectTitle { get; set; }
        public string LotNo { get; set; }
        public string ContractorName { get; set; }
        public string EvidofReg_Cac { get; set; }
        public string TaxClearanceCertificate { get; set; }
        public string EvidofReg_Bureau { get; set; }
        public string AudittedAccount { get; set; }
        public string ClearanceCert_Itf { get; set; }
        public string ClearanceCert_Pencom { get; set; }
        public string ClearanceCert_Nsitf { get; set; }
        public string StaffStrength { get; set; }
        public string CurrentFinStatus { get; set; }
        public string EquipmentList { get; set; }
        public string EvidPreSimJob { get; set; }
        public string ExpCompt { get; set; }
        public string FinalScore { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
