//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintForm
    {
        public string EmployeeCode { get; set; }
        public string FormType { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsIssued { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
