//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPayment
    {
        public int SalaryPaymId { get; set; }
        public int EmployeeCode { get; set; }
        public decimal SalaryAmount { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public Nullable<decimal> AllowanceAmount { get; set; }
        public Nullable<decimal> OtherDeduction { get; set; }
        public Nullable<decimal> OtherAllowance { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsSalarySlipPrint { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
