//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMaster
    {
        public int RecordId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string BatchNo { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> UomId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string PInvoiceNo { get; set; }
        public Nullable<System.DateTime> ReciveDate { get; set; }
        public string TotalPrice { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
