//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreReciptVoucher
    {
        public int RecordId { get; set; }
        public string VoucherId { get; set; }
        public string DepartmentId { get; set; }
        public string Store { get; set; }
        public Nullable<System.DateTime> DateIns { get; set; }
        public string ReceviedFrom { get; set; }
        public string Item { get; set; }
        public string Vendor { get; set; }
        public string Uom { get; set; }
        public string Qunatity { get; set; }
        public string Rate { get; set; }
        public string TotalValue { get; set; }
        public string BatchDetail { get; set; }
        public string StoreOfficer { get; set; }
        public string RecivingPerson { get; set; }
        public string Sign1 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Sign2 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Sign3 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
