//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreGateVoucher
    {
        public int RecordId { get; set; }
        public string VoucherTo { get; set; }
        public string LPONo { get; set; }
        public string VoucherFrom { get; set; }
        public string VoucherId { get; set; }
        public string Store { get; set; }
        public Nullable<System.DateTime> DateIns { get; set; }
        public string Deliver { get; set; }
        public string vehcileNo { get; set; }
        public string Item { get; set; }
        public string Vendor { get; set; }
        public string Uom { get; set; }
        public string Qunatity { get; set; }
        public string Rate { get; set; }
        public string TotalValue { get; set; }
        public string Sign1 { get; set; }
        public string OutOfStock { get; set; }
        public string LowStock { get; set; }
        public string Description { get; set; }
        public string Fund { get; set; }
        public string ShortSupply { get; set; }
        public string Reciving { get; set; }
        public string Fac { get; set; }
        public string Depart { get; set; }
        public string Date1 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
