//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TendererInformation
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string LotNo { get; set; }
        public string ProjectTitle { get; set; }
        public string RepresentativeName { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string YearofProject { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
