//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenderOpening
    {
        public int Id { get; set; }
        public string RepresentativeName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<decimal> AmountQuoted { get; set; }
        public Nullable<System.DateTime> CompletionPeriodFrom { get; set; }
        public Nullable<System.DateTime> CompletionPeriodTo { get; set; }
        public string Remarks { get; set; }
        public string LotNo { get; set; }
        public string ProjectTitle { get; set; }
        public string YearofProject { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
