//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UomMaster
    {
        public int RecordId { get; set; }
        public string UOMCode { get; set; }
        public string UOMName { get; set; }
        public string UOMDesc { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UOMStatus { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
