//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IARTAutomationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaster
    {
        public int RecordId { get; set; }
        public string VendorName { get; set; }
        public string VendorOrg { get; set; }
        public string VendorMob { get; set; }
        public string VendorAMob { get; set; }
        public string VendorEmail { get; set; }
        public string VendorRepDesc { get; set; }
        public string VendorAdd1 { get; set; }
        public string VendorAdd2 { get; set; }
        public Nullable<int> VendorCity { get; set; }
        public Nullable<int> VendorState { get; set; }
        public Nullable<int> VendorCountry { get; set; }
        public string VendorZipCode { get; set; }
        public string VendorTaxDet { get; set; }
        public string VendorDesc { get; set; }
        public Nullable<int> VendorStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CustomerId { get; set; }
    }
}
