DELETE FROM BankMaster
DELETE FROM CadreMaster
DELETE FROM PFAMaster
DELETE FROM ProgrammeMaster
DELETE FROM RankMaster
DELETE FROM SectionMaster
DELETE FROM StationMaster
DELETE FROM UnitResearchMaster
DELETE FROM UnitServicesMaster
DELETE FROM EmployeeGI
DELETE FROM CustomerMaster
DELETE FROM UserMaster
